{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:48:37.437Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:48:37.437Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:48:59.623Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:48:59.623Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:08.863Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:08.863Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:26.398Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:26.398Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:32.948Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:49:32.948Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:50:08.512Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:50:08.512Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:50:29.067Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:50:29.067Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:52:20.638Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:52:20.638Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:52:27.290Z'
}
{
  message: 'fake1 - something failed in index',
  level: '\u001b[31merror\u001b[39m',
  meta: Error: fake1 - something failed in index
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:12:9
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-10T02:52:27.290Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-17T11:04:26.861Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-17T11:04:26.861Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T02:30:27.414Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T02:30:27.414Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T06:12:47.888Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T06:12:47.888Z'
}
{
  message: 'option expires is invalid',
  level: '\u001b[31merror\u001b[39m',
  meta: TypeError: option expires is invalid
      at Object.serialize (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\node_modules\cookie\index.js:145:13)
      at ServerResponse.res.cookie (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\response.js:853:36)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:53:9
      at async C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:13,
  service: 'user-service',
  timestamp: '2021-01-20T09:17:20.054Z'
}
{
  message: 'option expires is invalid',
  level: '\u001b[31merror\u001b[39m',
  meta: TypeError: option expires is invalid
      at Object.serialize (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\node_modules\cookie\index.js:145:13)
      at ServerResponse.res.cookie (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\response.js:853:36)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:53:9
      at async C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:13,
  service: 'user-service',
  timestamp: '2021-01-20T09:17:20.054Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T09:17:20.452Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T09:17:20.452Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T09:27:58.943Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T09:27:58.943Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:05:23.164Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:05:23.164Z'
}
{
  message: 'userLogged is not defined',
  level: '\u001b[31merror\u001b[39m',
  meta: ReferenceError: userLogged is not defined
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:17:65
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-20T10:32:22.044Z'
}
{
  message: 'userLogged is not defined',
  level: '\u001b[31merror\u001b[39m',
  meta: ReferenceError: userLogged is not defined
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\routes\index.js:17:65
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\middleware\asyncMiddleware.js:5:19
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\route.js:112:3)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at Function.handle (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:47:12)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13),
  service: 'user-service',
  timestamp: '2021-01-20T10:32:22.044Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:33:38.367Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:33:38.367Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:49:17.486Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:49:17.486Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:49:39.763Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:49:39.763Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:50:23.167Z'
}
{
  message: 'Not Found',
  level: '\u001b[31merror\u001b[39m',
  meta: ClientError [NotFoundError]: Not Found
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\app.js:84:8
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at compression (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\compression\index.js:220:5)
      at newFn (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express-async-errors\index.js:16:20)
      at Layer.handle [as handle_request] (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:317:13)
      at C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:284:7
      at Function.process_params (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\express\lib\router\index.js:275:10)
      at internalNext (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\index.js:79:17)
      at xXssProtectionMiddleware (C:\Users\Mert\Documents\web_development\Projects\generated-feedback-app\node_modules\helmet\dist\middlewares\x-xss-protection\index.js:6:9),
  service: 'user-service',
  timestamp: '2021-01-20T10:50:23.167Z'
}
